import type { Metadata } from "next";
import { Baloo_Da_2 } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const baloo_da_2 = Baloo_Da_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body className={`${baloo_da_2.variable} ${baloo_da_2.variable} antialiased`}>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
